### ISSUE TITLE
rebar compile won't work

### ISSUE THREAD

**Issue by si14** [msantos/gen_icmp#1]
> rebar compile 
> ==> procket (compile)
> /usr/bin/ld: cannot find -lancillary
> collect2: ld returned 1 exit status
> ERROR: cc c_src/procket.o  -Lc_src -lancillary -shared  -L/usr/local/lib/erlang/lib/erl_interface-3.7.4/lib -lerl_interface -lei -o priv/procket.so failed with error: 1

**Comment by segachan** [comment]
@msantos 
Hello. 
@msantos Hello. I'm facing this issue. I don't know why, this issue is reproduced when there is `-j` option of `make` command, is not reproduced when there is no `-j` it.

```
FROM arm64v8/erlang:24.0-alpine@sha256:8ba9ec67f5b54bf3a659238a77b9555b0ac8373dc855c008147b67690a69c8f2
```
