### ISSUE TITLE
Build on OS X

### ISSUE THREAD

**Issue by kradalby** [msantos/gen_icmp#11]
Hi

Currently building procket is broken on at least OS X, this is resolved in the procket master branch.

Procket has not been released with the new rebar3 commit which solves the OS X building.

Would it be possible to either push a new version of procket or to switch to procket master?

Also, to send ICMP on OS X, i need to start the Erlang VM with root privileges, is there a workaround for this?

**Comment by msantos** [comment]
@kradalby thanks for letting me know! I will upgrade the dep.

As for avoiding root privs: the choices usually are either setting up a password-less sudo or making the procket helper setuid. There's more detail in the procket README but it's something like:
~~~
myuser ALL = NOPASSWD: /path/to/procket/priv/procket
~~~ 
If you run into problems with that or have any questions or comments, please let me know!

**Comment by kradalby** [comment]
Ok, I will look into it when it comes to deployment :)

Great work with both procket and gen_icmp!

**Comment by kradalby** [comment]
Thank you for quick support, I have changed back to the master branch, and now it works like a charm !

Keep up the good work :)
