### ISSUE TITLE
How to make use of Elapsed value in response

### ISSUE THREAD

**Issue by vimal7370** [msantos/gen_icmp#12]
I always get big negative values for Elapsed. Is this fine? How can I make use of it? (like converting it to ms as in ping):

49> gen_icmp:ping(["google.com"]).
[{ok,"google.com",
     {216,58,220,14},
     {216,58,220,14},
     {29619,0,55,-4294971590971590814},
     <<" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJK">>}]
50> gen_icmp:ping(["google.com", "google.com", "google.com"]).
[{ok,"google.com",
     {216,58,220,14},
     {216,58,220,14},
     {29619,0,55,-4294971590971590871},
     <<" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJK">>},
 {ok,"google.com",
     {216,58,220,14},
     {216,58,220,14},
     {29619,1,55,-4294971590971590871},
     <<" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJK">>},
 {ok,"google.com",
     {216,58,220,14},
     {216,58,220,14},
     {29619,2,55,-4294971590971590872},
     <<" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJK">>}]

$ ping google.com
PING google.com (216.58.220.14): 56 data bytes
64 bytes from 216.58.220.14: icmp_seq=0 ttl=56 time=87.072 ms
64 bytes from 216.58.220.14: icmp_seq=1 ttl=56 time=89.757 ms
64 bytes from 216.58.220.14: icmp_seq=2 ttl=56 time=90.696 ms
64 bytes from 216.58.220.14: icmp_seq=3 ttl=56 time=89.885 ms
64 bytes from 216.58.220.14: icmp_seq=4 ttl=56 time=89.419 ms
^C
--- google.com ping statistics ---
5 packets transmitted, 5 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 87.072/89.366/90.696/1.221 ms

**Comment by msantos** [comment]
Thanks for reporting this @vimal7370! The problem was buggy sign conversion if erlang:monotonic_time/1 returned a negative integer.

I've reverted the code to os:timestamp/0. Thanks again and if you run into any more problems or have any questions, please let me know!
