### ISSUE TITLE
ipv6 works on linux, but not on mac

### ISSUE THREAD

**Issue by mymindishazel** [msantos/gen_icmp#20]
heya,
i'm trying to use this to send ipv6 icmp ping requests using
```erl
gen_icmp:ping("dns.google", [inet6])
```

this works perfectly fine on linux, but errors with `enoprotoopt` on mac -- both machines are in the same network and have a valid IPv6 address assigned to them

what would be the steps to get this working on macos, or what information would you need to figure out why it's not working?

**Comment by msantos** [comment]
Does this patch fix ICMP6 pings for you?

```diff
diff --git a/src/gen_icmp.erl b/src/gen_icmp.erl
index 7a88646..461b149 100644
--- a/src/gen_icmp.erl
+++ b/src/gen_icmp.erl
@@ -699,7 +699,13 @@ ipv6_unicast_hops() ->
         {unix, _} -> 4
     end.

-icmp6_filter() -> 1.
+icmp6_filter() ->
+    case erlang:system_info(os_type) of
+        {unix, linux} ->
+            1;
+        {unix, _} ->
+            18
+    end.

 % IPv6 ICMP filtering
 %
```

ICMP6_FILTER is set to 18 on FreeBSD and Mac OS X. On a FreeBSD system, before the patch, I was also seeing `{error, enoprotoopt}`.

After:

```
1> gen_icmp:ping("google.com", [inet6]).                             
[{ok,"google.com",    
     {9735,63664,16393,2057,0,0,0,8206},                            
     {9735,63664,16393,2057,0,0,0,8206},                            
     {22654,0,4294967295,188},
     <<" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNO">>}]
```

**Comment by mymindishazel** [comment]
Works like a charm! You are a wizard.

(also, hey, as a very young dev, this is the first ever patch I've received via email :D)
